baseURL = "https://alphatradeengineering.com/"
title = 'Alpha Trade Engineering LLC'
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancytitle = '<img height="128" src="/images/logo.png" alt="Logo"/><br />Aplha Trade Engineering LLC'
copyright = "Alpha Trade Engineering LLC. All Rights Reserved."
startbuttonLink = "#contact"

[markup.goldmark.renderer]
unsafe = true

[languages.en]
weight = 10
languageName = "English"
description = "Welcome to Alpha Trade Engineering, LLC, a systematic multi-strategy hedge fund applying quantitative research to global markets."
startbuttonText = "Inquiries"

# menu

## english

[[languages.en.params.menu.main]]
url = '/'
title = "Home"

[[languages.en.params.menu.main]]
url = '/#one'
title = "About Us"

[[languages.en.params.menu.main]]
url = '/#two'
title = "Different"

[[languages.en.params.menu.main]]
url = '/#three'
title = "The Team"


# first section
## english

[languages.en.one]
enable = true
title = 'About Us'
body = "A multi-strategy systematic fund built to generate uncorrelated alpha across volatility, macro, and equity markets — with strategies proven to perform in the most challenging market regimes.<br><br>At Alpha Trade Engineering, we combine deep quantitative research with disciplined execution to deliver consistent, risk-managed returns. Our approach reflects over a decade of quantitative portfolio management experience, a verifiable long-term live track record, and the agility of a founder-led firm."


#[[languages.en.one.icon]]
##icon = "fa-wheelchair-alt"
#style = "1"
#label = "for wheelchair users"
#
#[[languages.en.one.icon]]
##icon = "fa-clock-o"
#style = "2"
#label = "fast setup"
#
#[[languages.en.one.icon]]
##icon = "fa-wrench"
#style = "3"
#label = "no tools"
#
# second section
## english

[languages.en.two]
enable = true
title = "What Makes Us Different"
#body = "What Makes Us Different"
#body = 'The Fund Managers’ track record includes delivering a 28% net compound annual return over nearly 10 years, with assets under management ranging from $20M to over $100M.'


[[languages.en.two.section]]
img = "images/pic1.png"
#title = 'Easy to use'
body = "Multi-Strategy Depth: Most emerging managers launch with a single idea. We begin with three distinct, research-backed strategies — Volatility, Systematic Macro, and Intraday Trend Capture — all proven to be uncorrelated with the broader market, and each designed to capture different market opportunities and reduce reliance on any one source of returns."

[[languages.en.two.section]]
img = "images/pic2.png"
#title = 'modular system'
body = "Resilience in Challenging Markets: Our models are specifically engineered for stressed environments — when volatility spikes, correlations break down, and liquidity thins. By design, the Fund is positioned to seek opportunities precisely when many strategies falter."

[[languages.en.two.section]]
img = "images/pic3.png"
#title = 'use in leisure or integration'
body = "Institutional Rigor, Boutique Agility: Our leadership team brings over a decade of experience managing institutional money leveraging our advanced analytical techniques and resulting quantitative strategies. We apply that same rigor to portfolio construction and risk management, while maintaining the agility to capitalize on inefficiencies overlooked by larger firms."

[[languages.en.two.section]]
img = "images/pic4.png"
#title = 'Start Ab system'
body = "Uncorrelated Alpha: By blending strategies across volatility carry, macro factor trends, and intraday equity dispersion, we deliver genuinely uncorrelated sources of alpha. The result is a more balanced, diversifying return stream for investors seeking alternatives beyond traditional equity and hedge fund exposures."


# third section

## english

[languages.en.three]
enable = true
title = "Meet the Team"
body = "The Fund Managers’ track record includes delivering a 28% net compound annual return over nearly 10 years, with assets under management ranging from $20M to over $100M."

[[languages.en.three.feature]]
img = "images/jim.jpeg"
title = "Jim Stephanou"
body = "Chief Executive Officer<br><br>Mr. Stephanou shares leadership responsibilities for research and development, with a focus on designing and refining quantitative trading strategies. He has deep expertise in financial analysis, advanced statistical and econometric analysis, artificial intelligence and machine learning, and multi-asset trading. Jim is passionate about applying cutting-edge analytical techniques in finding true alpha.<br><br>He holds a BS in Business Administration from the University of Illinois at Urbana–Champaign and an MBA in Finance, Strategy, and International Business from the Kellogg School of Management at Northwestern University"

[[languages.en.three.feature]]
img = "images/david.jpeg"
title = "David Juday"
body = "Chief Investment Officer<br><br>Mr. Juday shares leadership responsibilities for Portfolio Management, overseeing strategy design, refinement, and the research and development of new systematic approaches. He brings over a decade of specialized expertise in long/short volatility and systematic macro strategies, with a history of delivering strong, risk-adjusted returns across diverse market regimes.<br><br>He holds an MBA in Finance from Missouri State University. Earlier in his career, he also pursued advanced theological studies, earning both a BA and a Master of Divinity"

[[languages.en.three.feature]]
img = "images/jamie.jpeg"
title = "Jamie Kurtz"
body = "Chief Techology Officer<br><br>Mr. Kurtz is responsible for all technology and operations at the Fund, including the research and development platform and API-based trade execution systems. He also oversees the Fund’s cloud-based, high-volume data architecture, supporting advanced analytics and secure data storage. In addition, he leads performance monitoring and reporting.<br><br>He holds a BS in Physics, Mathematics, and Computer Science from Western Michigan University."


# buy or die

## english

[languages.en.cta]
enable = false
title = "Wanna play ninepins?"
	body = "Here you can buy Kegelschiene or – to find out more – have a look at some pictures in our gallery."

[[languages.en.cta.link]]
href = "#contact"
text = "Contact"
special = true

[[languages.en.cta.link]]
href = "https://gallery.kegelschiene.net/"
text = "Gallery"
special = false

[languages.en.contact]
enable = true
title = "Inquiries"
#phone = "+49 (0) 9848 744"
email = "info@alphatradeengineering.com"
#body = 'Contact us for questions and orders. <a href="/pricing/">You cand find out more about the <strong>pricing</strong> here</a>. Please remember to mention your address and payment details in your order.'
address = "3740 N Mozart St. </br>Chicago, IL 60618"
subject = "Investment inquries"
formspree_form_id = "123ijd"


